config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    resources :products do
      resources :reviews
    end
  end
  devise_for :users
  root 'categories#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  validates_uniqueness_of :name
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates_presence_of :title
  # validates_presence_of :user_id
  validates_presence_of :description
  validates_presence_of :price
  validates_format_of :price, :with => /\A^\d+\.?\d{0,2}\z/
  belongs_to :category
  belongs_to :user
  has_many :reviews
  # lol = 2
  def average_rating()
    # a = Product.find(id).review.last
    sum = 0
    # r = Review.where(:product_id => self.id)
    # r = Product.find(self.id).reviews
    r = self.reviews
    r.each do |a|
      sum += a.rating
      # print sum
    end
    return (sum.to_f / r.length.to_f)
    # return sum
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
  
  # def author
  #   return self.user.firstname.to_s + ' ' + self.user.lastname.to_s
  # end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates_presence_of :firstname
  validates_presence_of :lastname
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews
  has_many :products
end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  before_action :get_latest_products
  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protected

  def configure_devise_permitted_parameters
    registration_params = [:firstname, :lastname, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
  end


  def get_latest_products
    @kupa = 'kupa'
    if Product.last(2)
      @last_added = Product.last(2) 
    else
      @last_added = ['Not enough products', 'Not enough products']
    end
  end 
  

  def auth_user
    if user_signed_in?
      unless Product.find(params[:id]).user_id == current_user.id
        redirect_to category_product_path(params[:category_id], params[:id]), :error => 'You are not allowed to edit this product.'
        return false
      else
        return true
        
      end
    else
      return false
    end
  end

  def get_current_user
    if user_signed_in?
      @curr = current_user
    end
  end

  def authenticate_admin
    unless current_user.try(:admin?)
      # redirect_to new_user_session_path, :error => "Not an admin!"
      redirect_to new_user_session_path
      # , :error => "Not an admin!" === TO NIE ZADZIAUA
      flash[:error] = "You're not an admin"
      return false
      
    else
      return true
    end    
  end

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  protect_from_forgery with: :exception
end
  # def authenticate_recruit
  #   unless session[:recruit_id]
  #     redirect_to(:controller => 'recruit', :action => 'auth')
  #     return false
  #   else
  #     @current_recruit = Recruit.find session[:recruit_id] 
  #     return true
  #   end
  # end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  layout "testing"  
  def index
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :create]
  before_action :authenticate_admin, only: [:new, :edit, :create, :update]
  expose(:categories)
  expose(:category)
  expose(:product) { Product.new }

  def index
  end

  def show
  end

  def new 
  end

  def edit
  end

  def create
    self.category = Category.new(category_params)

    if category.save
      redirect_to category, notice: 'Category was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if category.update(category_params)
      redirect_to category, notice: 'Category was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:update, :create, :destroy]
  # before_action :auth_user, only: [:update, :edit, :destroy]
  before_action :get_current_user
  expose(:category)
  expose(:products)
  expose(:product)
  expose(:review) { Review.new }
  expose_decorated(:reviews, ancestor: :product)

  def index
    products = Product.all
  end

  def show
  end

  def new
    @category = Category.find(params[:category_id])
  end

  def edit
    # @eko = session
    # @eko = session
    # @eko.each do |e|
    wpis = self.product.attributes.to_s
    # @eko = @current_
    if user_signed_in?
      if Product.find(params[:id]).user_id != current_user.id
        redirect_to category_product_path(params[:category_id], params[:id]), :flash => { :error => 'You are not allowed to edit this product.' }
        # flash[:error] = 'You are not allowe1d to edit this product.'
      else
        # flash[:error] = 'else wewn '+wpis+' ok.'+current_user.email
      end         
    end
    
    # self.product = Product.find(params[:id])
    # p = Product.find(params[:id])
    
    # @ses_id = 213

  end

  def create
    self.product = Product.new(product_params)
    self.product.user_id = current_user.id

    if product.save
      category.products << product
      redirect_to category_product_path(category, product), notice: 'Product was successfully created.'
    else
      render action: 'new'
    end
  end

  def update      
    if user_signed_in?
      if Product.find(params[:id]).user_id != current_user.id
        redirect_to category_product_path(params[:category_id], params[:id]), :flash => { :error => 'You are not allowed to edit this product.' }
      else
        if self.product.update(product_params)
          redirect_to category_product_url(category, product), notice: 'Product was successfully updated.'
        else
          render action: 'edit'
        end
      end         
    end
    # if self.product.update(product_params)
    #   redirect_to category_product_url(category, product), notice: 'Product was successfully updated.'
    # else
    #   render action: 'edit'
    # end
    
  end

  # DELETE /products/1
  def destroy
    product.destroy
    redirect_to category_url(product.category), notice: 'Product was successfully destroyed.'
  end

  private
    def product_params
      params.require(:product).permit(:title, :description, :price, :category_id)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :get_current_user
  expose(:review)
  expose(:product)

  def edit
  end

  def create
    self.review = Review.new(review_params)
    review.user_id = current_user.id
    if review.save
      product.reviews << review
      redirect_to category_product_url(product.category, product), notice: 'Review was successfully created.'
    else
      render action: 'new'
    end
  end

  def destroy
    review.destroy
    redirect_to category_product_url(product.category, product), notice: 'Review was successfully destroyed.'
  end

  private
    def review_params
      params.require(:review).permit(:content, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/base/index.haml
WITAM. JEDNAK COŚ DZIAŁA.

app/views/categories/_form.html.haml
= form_for category do |f|
  - if category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
%h1 Listing categories

%table.table
  %tr
    %th Name
    %th Show
    %th Edit
    %th Destroy

  - categories.each do |category|
    %tr
      %td= category.name
      %td
        = link_to category do 
          %span.glyphicon.glyphicon-search
      %td
        = link_to edit_category_path(category) do
          %span.glyphicon.glyphicon-wrench
      %td
        = link_to category, method: :delete, data: { confirm: 'Are you sure?' } do
          %span.glyphicon.glyphicon-remove
       
%br


= link_to new_category_path do
  .btn.btn-default.btn-sm    
    
    New Category &nbsp
    %span.glyphicon.glyphicon-plus

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = category.name

%p
  - category.products.each do |product|
    = product.title

%p
  %h3 New product
  = render 'products/form'

= link_to 'Edit', edit_category_path(category)
\|
= link_to 'Back', categories_path

app/views/layouts/_header.haml
%ul.nav.nav.nav-tabs{:role => "tablist"}

  %li= link_to "Application", root_path

  %li{:class => [params[:controller], params[:action]] == ["products", "index"] ? "active" : ""}
    = link_to 'Products', category_products_path(:category_id => '1')
  / .dropdown{:class => [params[:controller], params[:action]] == ["products", "index"] ? "active" : ""}
      
  / %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
  /   Products
      
  /   %span.caret
  / %ul.dropdown-menu{:role => "menu"}
  /   -Category.all.each do |c|
  /     %li= link_to c.name, category_products_path(:category_id => c.id)
  /   %li.divider
  / %li= link_to 'All', category_products_path(:category_id => '1')

  
  %li{:class => [params[:controller], params[:action]] == ["categories", "index"] ? "active" : ""}= link_to "Categories", categories_path

  %li{:class => params[:controller] == "devise/sessions" ? "active" : ""}
    -if user_signed_in?
      = link_to "Sign out", destroy_user_session_path, method: :delete
    -else
      = link_to "Sign in", new_user_session_path 

  -if user_signed_in?

    %li{:class => [params[:controller], params[:action]] == ["devise/registrations", "edit"] ? "active" : ""}= link_to "Edit user", edit_user_registration_path
     
    %li.dropdown{:class => [params[:controller], params[:action]] == ["products", "new"] ? "active" : ""}
      
      %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
        Add product
        
        %span.caret
      %ul.dropdown-menu{:role => "menu"}
        -Category.all.each do |c|
          %li= link_to c.name, new_category_product_path(:category_id => c.id)
        

    %li{:class => [params[:controller], params[:action]] == ["categories", "new"] ? "active" : ""}= link_to "Add category", new_category_path

app/views/layouts/application.haml
!!!
%html{ lang: 'en' }
  %head
    %meta{ charset: 'utf-8' }/
    %meta{ content: 'IE=Edge,chrome=1', 'http-equiv' => 'X-UA-Compatible' }/
    %meta{ content: 'width=device-width, initial-scale=1.0', name: 'viewport' }/
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: "all", "data-turbolinks-track" => true 
    = javascript_include_tag 'application', "data-turbolinks-track" => true 
    = csrf_meta_tags 

  %body

    
    .container
      .row
        .col-md-1
        
        .col-md-10
          .middle-outside
            .header-img
              %img.logo-img{:src => image_path("man-reading.jpg")}
              / %img.logo-img{:alt => "Young Man Reading Book", :border => "0", :src => "http://thumbs.dreamstime.com/x/young-man-reading-book-portrait-over-retro-background-36367242.jpg"}
            .header-div
              = render 'layouts/header'

            .middle
              / %p#error= flash[:error]
              / %p.notice= notice
              %p.notice= alert 
              = yield
              %br
              %br
              %br
              %br
              %br
              %h4.centered
                %br
                Lastly added:
              -@last_added.each do |last_added_product|
                .col-md-6
                  .jumbotron                    
                    %b=last_added_product.title
                    %br=last_added_product.description
                    %br
                      Average rating:
                      =last_added_product.average_rating

                                  
            %div{:style => "background-color: rgba(100,100,100,0.4); position: absolute; right: 10px; bottom:10px; "}
              .small= params
              -if user_signed_in?
                .small= current_user.id
            %br
            %br

            %br
            %br
            %br
            %br
            %br
            %br
            %br
            %br
            %br
            %br
            %br
            %br
            %br
        .col-md-1
      .col-md-1
      .col-md-10
        .justified 
          %br
          &nbsp &nbsp &nbsp &nbsp Lorem ipsum &nbsp &nbsp &nbsp &nbsp | &nbsp &nbsp &nbsp &nbsp vertitus &nbsp &nbsp &nbsp &nbsp | &nbsp &nbsp &nbsp &nbsp habarentum &nbsp &nbsp &nbsp &nbsp | &nbsp &nbsp &nbsp &nbsp aquas &nbsp &nbsp &nbsp &nbsp | &nbsp &nbsp &nbsp &nbsp Lorem &nbsp &nbsp &nbsp &nbsp | &nbsp &nbsp &nbsp &nbsp ipsum vertitus &nbsp &nbsp &nbsp &nbsp 
      .col-md-1
         
      %br
      %br
      %br
      %br   
      %br
  .bottomer    
    %br
    %br
    %br
    .centered
      Lorem ipsum vertitus habarentum aquas. Lorem ipsum vertitus habarentum aquas. Lorem ipsum vertitus habarentum aquas
    
    %br
    %br

   

app/views/layouts/testing.haml
!!!
%html{ lang: 'en' }
  %head
    %meta{ charset: 'utf-8' }/
    %meta{ content: 'IE=Edge,chrome=1', 'http-equiv' => 'X-UA-Compatible' }/
    %meta{ content: 'width=device-width, initial-scale=1.0', name: 'viewport' }/
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: "all", "data-turbolinks-track" => true 
    = javascript_include_tag 'application', "data-turbolinks-track" => true 
    = csrf_meta_tags 

  %body

    .container
      
      %p#error= flash[:error]
      %p.notice= notice
      %p.notice= alert 
      = yield
      %div{:style => "background-color: rgba(100,100,100,0.4); position: absolute; right: 10px; bottom:10px; "}
        .small= params
    
    

app/views/products/_form.html.haml
= form_for [category, product] do |f|
  - if product.errors.any?
    #error_explanation
      %h2= "#{pluralize(product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - product.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :price
    = f.text_field :price
  .actions
    = f.submit 'Save'

app/views/products/edit.html.haml
%h1 Editing product
%p#error= flash[:error]
=@eko
/ = render 'form'
= form_for [category, product], method: :patch do |f|
  - if product.errors.any?
    #error_explanation
      %h2= "#{pluralize(product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - product.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :price
    = f.text_field :price
  .actions
    = f.submit 'Save'

= link_to 'Show', category_product_path(category, product)
\|
= link_to 'Back', category_path(category)

app/views/products/index.html.haml
%h1 Listing products

%table.table
  %tr
    %th Title
    %th Description            
    %th Price
    %th Category
    %th Show
    %th Edit
    %th Destroy

  - products.each do |product|
    %tr
      %td= product.title
      %td= product.description      
      %td= product.price
      %td= product.category.name
      %td
        = link_to category_product_path(product.category, product) do 
          %span.glyphicon.glyphicon-search
          
      %td
        = link_to edit_category_product_path(product.category, product) do
          %span.glyphicon.glyphicon-wrench
      %td
        = link_to category_product_path(product.category, product), method: :delete, data: { confirm: 'Are you sure?' } do
          %span.glyphicon.glyphicon-remove

%br

app/views/products/new.html.haml
%h1 New product
%label
  Category:
  =@category.name
= render 'form'

= link_to 'Back', category_products_path

app/views/products/show.html.haml
%p#notice= notice
%p#error= flash[:error]

%p
  %b Title:
  = product.title
%p
  %b Description:
  = product.description
%p
  %b Price:
  = product.price

%p
  %b Category
  = product.category.name

%p
  %b Reviews
  = render 'reviews/form'

= render reviews

= link_to 'Edit', edit_category_product_path(category.id, product.id)
\|
= link_to 'Back', category_products_path

app/views/reviews/_form.html.haml
= simple_form_for [category, product, review] do |f|
  - if review.errors.any?
    #error_explanation
      %h2= "#{pluralize(review.errors.count, "error")} prohibited this review from being saved:"
      %ul
        - review.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.input :rating, collection: 1..5
  .actions
    = f.submit 'Save'

app/views/reviews/_review.html.haml
%p= review.content
%p
  %b= review.rating
  %em= review.author